easy_admin:
    entities:
<<<<<<< HEAD
<<<<<<< HEAD
        - AppBundle\Entity\Ciudad
        - AppBundle\Entity\Oferta
        - AppBundle\Entity\Venta
        - AppBundle\Entity\Tienda
        - AppBundle\Entity\Usuario
||||||| parent of d67b65e (Eliminado el backend anterior y reemplazado por EasyAdmin)
=======
        - Cupon\CiudadBundle\Entity\Ciudad
        - Cupon\OfertaBundle\Entity\Oferta
||||||| parent of ab1dc88 (Eliminados todos los bundles para usar solo AppBundle)
        - Cupon\CiudadBundle\Entity\Ciudad
        - Cupon\OfertaBundle\Entity\Oferta
=======
        - AppBundle\Entity\Ciudad
        - AppBundle\Entity\Oferta
>>>>>>> ab1dc88 (Eliminados todos los bundles para usar solo AppBundle)
        #- Cupon\OfertaBundle\Entity\Venta
<<<<<<< HEAD
        - Cupon\TiendaBundle\Entity\Tienda
        - Cupon\UsuarioBundle\Entity\Usuario
>>>>>>> d67b65e (Eliminado el backend anterior y reemplazado por EasyAdmin)
||||||| parent of ab1dc88 (Eliminados todos los bundles para usar solo AppBundle)
        - Cupon\TiendaBundle\Entity\Tienda
        - Cupon\UsuarioBundle\Entity\Usuario
=======
        - AppBundle\Entity\Tienda
        - AppBundle\Entity\Usuario
>>>>>>> ab1dc88 (Eliminados todos los bundles para usar solo AppBundle)
