_backend:
    resource: '@EasyAdminBundle/Controller/'
    type:     annotation
    prefix:   /admin

_paginas:
    resource: routing_paginas.yml
    prefix:   /{_locale}/sitio
    requirements:
        _locale: en|es
    defaults:
        _locale: '%locale%'
        _controller: FrameworkBundle:Template:template
        private: false
        maxAge: 86400
        sharedMaxAge: 86400

app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en|es
    defaults:
        _locale: '%locale%'

_extranet:
    resource: '@AppBundle/Controller/ExtranetController.php'
    type:     annotation
    prefix:   /extranet

# Homepage redirect (no locale prefix)
# Redirects / to the default city's homepage
_portada:
     path:  /
     defaults:
          _controller: FrameworkBundle:Redirect:redirect
          route: portada
          ciudad: '%app.ciudad_por_defecto%'

_api:
    resource: '@AppBundle/Controller/ApiController.php'
    type:     annotation
    prefix:   /api
